/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasklistImport } from './routes/tasklist'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const AddTaskLazyImport = createFileRoute('/AddTask')()

// Create/Update Routes

const AddTaskLazyRoute = AddTaskLazyImport.update({
  id: '/AddTask',
  path: '/AddTask',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/AddTask.lazy').then((d) => d.Route))

const TasklistRoute = TasklistImport.update({
  id: '/tasklist',
  path: '/tasklist',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tasklist': {
      id: '/tasklist'
      path: '/tasklist'
      fullPath: '/tasklist'
      preLoaderRoute: typeof TasklistImport
      parentRoute: typeof rootRoute
    }
    '/AddTask': {
      id: '/AddTask'
      path: '/AddTask'
      fullPath: '/AddTask'
      preLoaderRoute: typeof AddTaskLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasklist': typeof TasklistRoute
  '/AddTask': typeof AddTaskLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasklist': typeof TasklistRoute
  '/AddTask': typeof AddTaskLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tasklist': typeof TasklistRoute
  '/AddTask': typeof AddTaskLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tasklist' | '/AddTask'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tasklist' | '/AddTask'
  id: '__root__' | '/' | '/tasklist' | '/AddTask'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasklistRoute: typeof TasklistRoute
  AddTaskLazyRoute: typeof AddTaskLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasklistRoute: TasklistRoute,
  AddTaskLazyRoute: AddTaskLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/tasklist",
        "/AddTask"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/tasklist": {
      "filePath": "tasklist.jsx"
    },
    "/AddTask": {
      "filePath": "AddTask.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
